{"name": "测试手机号码错误登录失败", "status": "passed", "attachments": [{"name": "log", "source": "324ec815-8284-4184-a1c0-7e5b8c6c8a88-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "adb5b074-d37a-4475-b09d-7488076792a9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ab402455-05fc-4ba1-82f8-fa942f8faa0d-attachment.txt", "type": "text/plain"}], "start": 1553240669514, "stop": 1553240699982, "uuid": "efbecb77-8cd7-4396-8db0-adbca1778175", "historyId": "e533257fa73d83df35674161f3a97b5a", "fullName": "test_case.test_bpm.test_login.TestLogin#test_login_failed_phone_error", "labels": [{"name": "feature", "value": "测试登录"}, {"name": "story", "value": "测试登录失败"}, {"name": "parentSuite", "value": "test_case.test_bpm"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "cadentang"}, {"name": "thread", "value": "15076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_bpm.test_login"}]}