{"uuid": "56dc9fc3-b893-4476-8ea5-59add0da7829", "children": ["2fda94b6-1a76-4064-a2ff-9bb5ac52629c"], "befores": [{"name": "_Class__pytest_setup_method", "status": "passed", "start": 1553479281755, "stop": 1553479291545}], "afters": [{"name": "_Class__pytest_setup_method::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestCustomerManageAdd' object has no attribute 'driver'\n", "trace": "  File \"D:\\softwore\\python372\\lib\\site-packages\\allure_commons\\_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\python.py\", line 777, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\softwore\\python372\\lib\\site-packages\\_pytest\\python.py\", line 691, in _call_with_optional_argument\n    func()\n  File \"D:\\my-git-project\\91lng\\selenium_91lng_auto_test\\test_case\\test_bpm\\test_customer_manage.py\", line 49, in teardown_method\n    self.driver.close()\n"}, "start": 1553479323721, "stop": 1553479323734}], "start": 1553479281755, "stop": 1553479323734}